name: test_flutter
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
    sdk: '>=2.17.6 <3.0.0'
dependencies:
  bloc: ^8.1.0
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  firebase_auth: ^4.2.6
  firebase_core: ^2.5.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  font_awesome_flutter: ^10.2.1
  sqflite: ^2.3.2
  image: ^4.0.15
  get_it: ^7.2.0
  http: ^1.1.0
  connectivity: ^3.0.6
  google_fonts: ^5.1.0
  hydrated_bloc: ^9.1.0
  image_picker: ^0.8.5+3
  intl_phone_field: ^3.1.0
  logger: ^1.1.0
  path_provider: ^2.0.11
  provider: ^6.0.3
  responsive_builder: ^0.5.1
  swipe_cards: ^2.0.0+1
  swipeable_card_stack: ^0.0.5
  google_sign_in: ^6.1.5
  uuid: ^3.0.6
  validators: ^3.0.0
  animated_text_kit: ^4.2.2
  firebase_storage: ^11.0.11
  step_progress_indicator: ^1.0.2
  lottie: ^2.6.0
dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^2.0.0
flutter:
    uses-material-design: true


  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
      
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
      
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
      
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages